### ISSUE TITLE
ADD troubleshooting to readme

### ISSUE THREAD

**Issue by andrewheusser** [sofroniewn/electron-johnny-five-examples#2]
Awesome job @sofroniewn!

aside from the serialport trouble, I had to upload the firmata standard firmware to my arduino to make it work.  I had some goofy custom code on there before.  It might be worth mentioning that in the readme.

This is from the johnny-five docs:

If the above didn't work as expected, make sure that StandardFirmata is installed on the board:

Download Arduino IDE
Plug in your Arduino or Arduino compatible microcontroller via USB
Open the Arduino IDE, select: File > Examples > Firmata > StandardFirmata
Click the "Upload" button.
If the upload was successful, the board is now prepared and you can close the Arduino IDE.

**Comment by sofroniewn** [comment]
@andyh616 Yes - great suggestion, I've updated the docs, thanks!
